ParkyWeb/Controllers/NationalParksController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ParkyWeb.Models;
using ParkyWeb.Repository.IRepository;

namespace ParkyWeb.Controllers
{
    [Authorize]
    public class NationalParksController : Controller
    {
        private readonly INationalParkRepository _nationalRepository;


        public NationalParksController(INationalParkRepository nationalRepository)
        {
            this._nationalRepository = nationalRepository;                              
        }


        public IActionResult Index()
        {
            return View(new NationalPark() { } );
        }


        /*
         * UpdateInsert() is used to update and insert a national park.
         * Id: a nullable id
         */
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> UpdateInsert(int? Id)
        {
            NationalPark park = new NationalPark();

            if (Id == null)
            {
                // this instruction will be treu for insert and create
                return View(park);

            }

            // load the object for update
            park = await this._nationalRepository.GetAsync(SDetail.NationalParkAPIpath, 
                    Id.GetValueOrDefault(), HttpContext.Session.GetString("JWToken"));

            if ( park == null)
            {
                return NotFound();
            }

            return View(park);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateInsert(NationalPark nationalPark)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;

                if (files.Count > 0)
                {
                    byte[] picture = null;

                    using (var file = files[0].OpenReadStream())
                    {
                        using (var stream = new MemoryStream())
                        {
                            file.CopyTo(stream);
                            picture = stream.ToArray();
                        }
                    }

                    nationalPark.Picture = picture;
                }
                else
                {
                    var parkFromDatabase = await this._nationalRepository
                                .GetAsync(SDetail.NationalParkAPIpath, nationalPark.Id,
                                HttpContext.Session.GetString("JWToken"));
                    nationalPark.Picture = parkFromDatabase.Picture;
                }

                if ( nationalPark.Id == 0)
                {
                    await this._nationalRepository.CreateAsync(SDetail.NationalParkAPIpath,
                        nationalPark, HttpContext.Session.GetString("JWToken"));
                }
                else
                {
                    await this._nationalRepository
                        .UpdateAsync(SDetail.NationalParkAPIpath+nationalPark.Id, 
                                  nationalPark, HttpContext.Session.GetString("JWToken"));
                }

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(nationalPark);
            }
        }


        [HttpDelete]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int Id)
        {
            var status = await this._nationalRepository
                                    .DeleteAsync(SDetail.NationalParkAPIpath, Id,
                                    HttpContext.Session.GetString("JWToken"));

            if (status)
            {
                return Json(new { success = true, message = "Delete successful" });
            }

            return Json(new { success = false, message = "Delete successful" });
        }


        public async Task<IActionResult> GetAllNationalPark()
        {
            return Json( new { data = await this._nationalRepository
                                      .GetAllAsync(SDetail.NationalParkAPIpath,
                                      HttpContext.Session.GetString("JWToken"))
            });
        }
    }
}

ParkyWeb/Controllers/TrailsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ParkyWeb.Models;
using ParkyWeb.Models.ViewModels;
using ParkyWeb.Repository.IRepository;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace ParkyWeb.Controllers
{
    [Authorize]
    public class TrailsController : Controller
    {
        private readonly ITrailRepository _trailRepository;
        private readonly INationalParkRepository _nationalParkRepository;


        public TrailsController(ITrailRepository trailRepository,
                                INationalParkRepository nationalRepository)
        {
            this._trailRepository = trailRepository;
            this._nationalParkRepository = nationalRepository;
        }


        public IActionResult Index()
        {
            return View(new Trail() { } );
        }


        /*
         * UpdateInsert() is used to update and insert a national park.
         * Id: a nullable id
         */
         [Authorize(Roles ="Admin")]
        public async Task<IActionResult> UpdateInsert(int? Id)
        {
            IEnumerable<NationalPark> nationalParks = await this._nationalParkRepository
                                        .GetAllAsync(SDetail.NationalParkAPIpath,
                                        HttpContext.Session.GetString("JWToken"));

            TrailsVM trailVM = new TrailsVM()
            {
                NationalParkList = nationalParks.Select(park => new SelectListItem
                {
                    Text = park.Name,
                    Value = park.Id.ToString()
                }),
                Trail = new Trail()
            };

            //var trailVM = await this.populateNationalParkDropDownm();

            if (Id == null)
            {
                // this instruction will be treu for insert and create
                return View(trailVM);

            }

            // load the object for update
            trailVM.Trail = await this._trailRepository.GetAsync(
                                SDetail.TrailAPIpath, Id.GetValueOrDefault(),
                                HttpContext.Session.GetString("JWToken"));

            if (trailVM.Trail == null)
            {
                return NotFound();
            }

            return View(trailVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateInsert(TrailsVM trailVM)
        {
            if (ModelState.IsValid)
            {
                if (trailVM.Trail.Id == 0)
                {
                    await this._trailRepository.CreateAsync(SDetail.TrailAPIpath,
                        trailVM.Trail, HttpContext.Session.GetString("JWToken"));
                }
                else
                {
                    await this._trailRepository
                        .UpdateAsync(SDetail.TrailAPIpath + trailVM.Trail.Id,
                               trailVM.Trail, HttpContext.Session.GetString("JWToken"));
                }

                return RedirectToAction(nameof(Index));
            }
            else
            {
                IEnumerable<NationalPark> nationalParks = await this._nationalParkRepository
                                       .GetAllAsync(SDetail.NationalParkAPIpath,
                                       HttpContext.Session.GetString("JWToken"));

                TrailsVM trailVMa = new TrailsVM()
                {
                    NationalParkList = nationalParks.Select(park => new SelectListItem
                    {
                        Text = park.Name,
                        Value = park.Id.ToString()
                    }),
                    Trail = trailVM.Trail
                };

                //var trailVMa = await this.populateNationalParkDropDownm();

                return View(trailVMa);
            }
        }


        private async Task<TrailsVM> populateNationalParkDropDownm()
        {
            IEnumerable<NationalPark> nationalParks = await this._nationalParkRepository
                                        .GetAllAsync(SDetail.NationalParkAPIpath,
                                        HttpContext.Session.GetString("JWToken"));

            TrailsVM trailVM = new TrailsVM()
            {
                NationalParkList = nationalParks.Select(park => new SelectListItem
                {
                    Text = park.Name,
                    Value = park.Id.ToString()
                }),
                Trail = new Trail()
            };

            return trailVM;
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int Id)
        {
            var status = await this._trailRepository
                                    .DeleteAsync(SDetail.TrailAPIpath, Id,
                                    HttpContext.Session.GetString("JWToken"));

            if (status)
            {
                return Json(new { success = true, message = "Delete successful" });
            }

            return Json(new { success = false, message = "Delete not successful" });
        }


        public async Task<IActionResult> GetAllTrail()
        {
            return Json( new { data = await this._trailRepository
                                      .GetAllAsync(SDetail.TrailAPIpath, 
                                      HttpContext.Session.GetString("JWToken"))
            } );
        }
    }
}

ParkyWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpAccessor


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] ParkyWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- https://cdn.datatables.net/ -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" />
    <!-- https://cdnjs.com/libraries/jqueryui-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <!-- https://cdnjs.com/libraries/toastr.js/latest -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-success mb-3">
            <div class="container">
                <a class="navbar-brand text-white-50" asp-area="" asp-controller="Home" 
                            asp-action="Index">
                    ParkyWeb
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" 
                        data-target=".navbar-collapse" 
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home"
                               asp-action="Index">
                                Home
                            </a>
                        </li>


                        @if (User.IsInRole("Admin") || User.IsInRole("test"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white"
                                   asp-controller="NationalParks" asp-action="Index">
                                    National Park
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white"
                                   asp-controller="Trails" asp-action="Index">
                                    Trail
                                </a>
                            </li>
                        }













                        @if (httpAccessor.HttpContext.Session.GetString("JWToken") != null
                                       && httpAccessor.HttpContext.Session
                                           .GetString("JWToken").ToString().Length >= 1)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white"
                                   asp-controller="Home" asp-action="LogOut">
                                    Log out
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white"
                                   asp-controller="Home" asp-action="Login">
                                    Login
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white"
                                   asp-controller="Home" asp-action="Register">
                                    Register
                                </a>
                            </li>

                        }








                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            @if (TempData["alert"] != null ) 
            {
                <div class="alert alert-danger alert-dismissible fade show " role="alert">
                    @TempData["alert"]
                    <button type="button" class="close" data-dismiss="alert"
                            aria-label="close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }

            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- https://cdnjs.com/libraries/jqueryui -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <!-- https://cdn.datatables.net/ -->
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <!-- https://cdnjs.com/libraries/toastr.js/latest -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/7e4dd45e91.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>